// export const SET_USER = "SAVE_USER";

export const USER_ACTIONS = {
  SET_USER: "SAVE_USER",
  LOGOUT_USER: "LOGOUT_USER",
};

export const NOTIFICATION_ACTIONS = {
  SET_USER_SESSION_EXPIRED_ERROR: "SET_USER_SESSION_EXPIRED_ERROR",
};
